export const API_DOMAIN = process.env.NEXT_PUBLIC_API_DOMAIN;
export const DATASET_1_END_POINT = process.env.NEXT_PUBLIC_DATASET_1_END_POINT;
export const DATASET_2_END_POINT = process.env.NEXT_PUBLIC_DATASET_2_END_POINT;
